name: CI

# Copied from https://github.com/kowainik/.github/blob/master/workflow-templates/ci.yml
# and the blog post https://kodimensional.dev/github-actions by @chshersh

# Trigger the workflow on push or pull request, but only for the master branch
on:
  pull_request:
  push:
    branches: [master]

jobs:
  cabal:
    name: ${{ matrix.os }} / ghc ${{ matrix.ghc }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # os: [ubuntu-latest, macOS-latest, windows-latest]
        os: [ ubuntu-latest ]
        cabal: ["3.4"]
        ghc:
          - "7.10"
          - "8.0"
          - "8.2"
          - "8.4"
          - "8.6"
          - "8.8"
          - "8.10"
          - "9.0"
        # exclude:
        #   - os: macOS-latest
        #     ghc: 8.8
        #   - os: macOS-latest
        #     ghc: 8.6
        #   - os: windows-latest
        #     ghc: 8.8
        #   - os: windows-latest
        #     ghc: 8.6

    steps:
    - uses: actions/checkout@v2
      if: github.event.action == 'opened' || github.event.action == 'synchronize' || github.event.ref == 'refs/heads/master'

    - uses: haskell/actions/setup@v1.2
      id: setup-haskell-cabal
      name: Setup Haskell
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: ${{ matrix.cabal }}

    - name: Freeze
      run: |
        cabal freeze

    - uses: actions/cache@v2
      name: Cache ~/.cabal/store
      with:
        path: ${{ steps.setup-haskell-cabal.outputs.cabal-store }}
        key: ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('cabal.project.freeze') }}

    - name: Install dependencies
      run: |
        cabal build all --only-dependencies

    - name: Build
      run: |
        cabal configure --enable-tests --enable-benchmarks --test-show-details=direct
        cabal build all

    - name: Test
      run: |
        cabal test all

    - name: Documentation
      run: |
        cabal haddock        

  # stack:
  #   name: stack / ghc ${{ matrix.ghc }}
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       stack: ["2.3.1"]
  #       ghc: ["8.8.3"]

  #   steps:
  #   - uses: actions/checkout@v2
  #     if: github.event.action == 'opened' || github.event.action == 'synchronize' || github.event.ref == 'refs/heads/master'

  #   - uses: actions/setup-haskell@v1.1
  #     name: Setup Haskell Stack
  #     with:
  #       ghc-version: ${{ matrix.ghc }}
  #       stack-version: ${{ matrix.stack }}

  #   - uses: actions/cache@v1
  #     name: Cache ~/.stack
  #     with:
  #       path: ~/.stack
  #       key: ${{ runner.os }}-${{ matrix.ghc }}-stack

  #   - name: Build
  #     run: |
  #       stack build --system-ghc --test --bench --no-run-tests --no-run-benchmarks

  #   - name: Test
  #     run: |
  #       stack test --system-ghc
